---
title: "GAMM Trials"
author: "Molly Wilson"
date: "1/6/2018"
output:
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 3
  pdf_document:
    toc: yes
---
```{r,message=FALSE,warning=FALSE}
library(rmarkdown)
library(dplyr)
library(nlme)
library(pls)
library(mgcv)
library(ggsignif)
```

```{r,message=FALSE,warning=FALSE}
setwd("~/github/Scarid-Behavior/data")
data <- read.csv("data2.csv", stringsAsFactors=FALSE)
vir<-data%>%filter(Species.Code=="stop") # Sparisoma viride only
vet<-data%>%filter(Species.Code=="qup") # Scarus vetula only
```

# Feeding rate (bites per hour)

## All species
```{r,message=FALSE,warning=FALSE}
gamm<-gamm(FR~Species+Phase+s(Length.cm)+s(scar.BM)+s(PC1)+s(PC2), family=gaussian(link=identity),data=data, random=list(Island=~1),method="REML")
summary(gamm$gam)
plot(gamm$gam,pages=1)
```

## Scarus vetula
```{r,message=FALSE,warning=FALSE}
gamm<-gamm(FR~Phase+s(Length.cm)+s(scar.BM)+s(PC1)+s(PC2), family=gaussian(link=identity),data=vet, random=list(Island=~1),method="REML")
summary(gamm$gam)
plot(gamm$gam,pages=1)
```

## Sparisoma viride
```{r,message=FALSE,warning=FALSE}
gamm<-gamm(FR~Phase+s(Length.cm)+s(scar.BM)+s(PC1)+s(PC2), family=gaussian(link=identity),data=vir, random=list(Island=~1),method="REML")
summary(gamm$gam)
plot(gamm$gam,pages=1)
```

# Fraction of time spent grazing

## All species
```{r,message=FALSE,warning=FALSE}
gamm<-gamm(g.frac~Species+Phase+s(Length.cm)+s(scar.BM)+s(PC1)+s(PC2), family=gaussian(link=identity),data=data, random=list(Island=~1),method="REML")
summary(gamm$gam)
plot(gamm$gam,pages=1)
```

## Scarus vetula
```{r,message=FALSE,warning=FALSE}
gamm<-gamm(g.frac~Phase+s(Length.cm)+s(scar.BM)+s(PC1)+s(PC2), family=gaussian(link=identity),data=vet, random=list(Island=~1),method="REML")
summary(gamm$gam)
plot(gamm$gam,pages=1)
```

## Sparisoma viride
```{r,message=FALSE,warning=FALSE}
gamm<-gamm(g.frac~Phase+s(Length.cm)+s(scar.BM)+s(PC1)+s(PC2), family=gaussian(link=identity),data=vir, random=list(Island=~1),method="REML")
summary(gamm$gam)
plot(gamm$gam,pages=1)
```
