---
title: 'Structural '
author: "Molly Wilson"
date: "3/14/2018"
output:
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 3
  pdf_document:
    toc: yes
---

```{r,message=FALSE,warning=FALSE, echo=FALSE}
# set up
library(rmarkdown)
library(dplyr)
library(tidyr)
library(lavaan)
library(semPlot)
```

```{r,message=FALSE,warning=FALSE, echo=FALSE}
setwd("~/github/Scarid-Behavior/data")
site.sum <- read.csv("site.sum.csv", stringsAsFactors=FALSE) %>% select(-X)
data <- read.csv("data2.csv", stringsAsFactors=FALSE)
# add aglal indeces
data <- data %>% mutate(index_MA = cover_MA*canopy_MA) %>% mutate(index_TA = cover_TA*canopy_TA)
# recode phase and species with dummy variables
data <- data %>% mutate(spec.dum= 
                          ifelse(Species.Code=="stop", 1, 
                          (ifelse(Species.Code=="qup", 2,
                          (ifelse(Species.Code=="rbp",3,NA)))))) %>%
  mutate(phase.dum=ifelse(Phase=="i",1,2))


```

```{r}
# define model pathways
model <- '
    FR ~ Length.cm + phase.dum + spec.dum+ int.scar + RISK + NUTRITION
    int.scar ~ scar.BM + cover_MA + cover_TA
    rugosity ~ cover_LC
    cover_LC ~ cover_MA + cover_TA
    cover_TA ~ scar.BM
    cover_MA ~ scar.BM
    
    RISK =~ scar.BM + rugosity
    NUTRITION =~ cover_MA + cover_TA
'

fit <- sem(model, data=data)
varTable(fit)
summary(fit, standardized=T, fit.measures=T,rsq=T)
semPaths(fit)
```

