---
title: 'Structural '
author: "Molly Wilson"
date: "3/14/2018"
output:
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 3
  pdf_document:
    toc: yes
---

```{r,message=FALSE,warning=FALSE, echo=FALSE}
# set up
library(here)
library(tidyverse)
library(lavaan)
library(semPlot)
```

```{r,message=FALSE,warning=FALSE, echo=FALSE}
sum_id <- read.csv(here("data","sum_id.csv"), stringsAsFactors=FALSE) %>% select(-X)
sum_site <- read.csv(here("data","sum_site.csv"), stringsAsFactors=FALSE) %>% select(-X)

# recode phase and species with dummy variables
# data <- data %>% mutate(spec.dum= 
#                           ifelse(Species.Code=="stop", 1, 
#                           (ifelse(Species.Code=="qup", 2,
#                           (ifelse(Species.Code=="rbp",3,NA)))))) %>%
#   mutate(phase.dum=ifelse(Phase=="i",1,2))


```

```{r}
# define model pathways
sem_full <- '
  # latent variable indicators
      risk =~ scar_bm_sc + rugosity_sc
      nutrition =~ ma_cover + ma_canopy + ta_cover + ta_canopy
  # regressions
      fr_sc ~ length_cm + risk + nutrition
      rugosity_sc ~ lc_cover
      lc_cover ~ ma_cover + ma_canopy + ta_cover + ta_canopy
      ta_cover ~ scar_bm_sc
      ma_cover ~ scar_bm_sc    
      ta_canopy ~ scar_bm_sc
      ma_canopy ~ scar_bm_sc 
'
```

```{r}
# testing partial SEMs

sem_df <- sum_id %>% 
  filter(island!="Barbuda") %>%
  select(fr, g_frac, species_code, phase, scar_bm, scar_den, carn30_bm, tot_bm, spear_daily, ma_cover, ma_canopy, ta_cover, ta_canopy, rugosity, int_scar, length_cm, lc_cover) %>% 
  mutate(phase_dum=ifelse(phase=="i",1,2),
         fr_sc = fr/100,
         scar_bm_sc = scar_bm/100,
         rugosity_sc = rugosity*10) %>%
  na.omit()
vet_df <- sem_df %>% filter(species_code=="qup")
vir_df <- sem_df %>% filter(species_code=="stop")

sem1 <- '
  # latent variable indicators
      risk =~ scar_bm_sc
      nutrition =~ ma_cover + ta_cover
  # regressions
      fr_sc ~ length_cm + phase_dum + nutrition + risk
'

sem2 <- '
  # latent variable indicators
      risk =~ scar_bm_sc + scar_den + rugosity_sc + spear_daily
      nutrition =~ ma_cover + ta_cover
  # regressions
      fr_sc ~ length_cm + phase_dum + nutrition + risk
      rugosity_sc ~ lc_cover
      lc_cover ~ ma_cover + ta_cover
'

sem3 <- '
  # latent variable indicators
      risk =~ scar_bm_sc + scar_den + spear_daily
      nutrition =~ ma_cover + ta_cover
  # regressions
      fr_sc ~ length_cm + phase_dum + nutrition + risk
      lc_cover ~ ma_cover + ta_cover
'


fit <- sem(sem3, data=vet_df, missing="ML", std.lv=T, orthogonal=T)
varTable(fit)
summary(fit, standardized=T, fit.measures=T, rsq=T)
semPaths(fit)
fitMeasures(fit, c("cfi","rmsea","srmr"))
```


